### ISSUE TITLE
One tree or a combination of trees

### ISSUE THREAD

**Issue by Akshay199456** [uhcs2320/hwSix#1]
Can we assume that after processing all the information in the input file we will only have one tree ( where each node is connected to the single tree ) or can multiple trees exist ( few nodes could be connected to the root of another tree )?

**Comment by aleman** [comment]
Yes, you can assume that it will be only one tree. (There's is only one root node).

**Comment by Akshay199456** [comment]
I wanted to clarify a couple of issues:

1. What are the maximum number of children nodes that a parent node can have?

2. There seems to be an error in the name of the file under program specification
![image](https://cloud.githubusercontent.com/assets/11953567/20634350/85c09d84-b315-11e6-8363-434fb961fe78.png)

The main program should be called "leaflead" and not "devhire".

**Comment by aleman** [comment]
4.

leaflead

**Comment by Akshay199456** [comment]
1. Can we use more than one data structure: a linked list in addition to a tree?

2. Also, given the current test case, there are a few instances where the nodes have the same score ( Skye and Director [1445] , Robot and Lex [1099], Supergirl and Superman [1636] ). In these cases, how would we decide which name to display first ( since the order in which they are stored in the tree decides the way they will be output if they have the same score ) ?

**Comment by aleman** [comment]
1. Yes

2. Your program will be tested with data where there aren't same scores.

**Comment by Akshay199456** [comment]
Will additional test cases be added?

**Comment by aleman** [comment]
Yes, added already.
